In [13]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [19]:
df = pd.read_csv("/Users/netrakc/Desktop/Data-Science/MachineLearning_Algorithms/KNearestNeighbors/heart.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [20]:
from sklearn.model_selection import train_test_split

X = df.iloc[:, 0:-1]
y = df.iloc[:, -1]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)

/opt/anaconda3/envs/ml-env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [22]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score, confusion_matrix

# Accuracy score : total number of correct prediction / total number of prediction. 

print("Accuracy of Logistic Regression: ", accuracy_score(y_test, y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression:  0.9016393442622951
Accuracy of Decision Trees 0.8688524590163934


In [25]:
# confusion matrix: tells the nature of the errors. 
confusion_matrix(y_test, y_pred1)

array([[26,  6],
       [ 0, 29]])

Observation:

- Model predict that 26 people have breast cancer and in real, 26 people have breast cancer.  
- Model predict that 6 people does not have cancer but 6 people have breast cancer in real.
- There is not a single people who does not have cancer, in real there is not a single person who does not have breast cancer. 
- Model predict that 29 people does not have cancer, And In real, 29 people does not have cancer. 

In [30]:
print("Decision Tree Confusion Matrix\n")
confusion_matrix(y_test,y_pred2)

Decision Tree Confusion Matrix



array([[26,  6],
       [ 2, 27]])

In [31]:
# Creating a dataframe to store the result. 
result = pd.DataFrame()

result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [32]:
result.sample(10)

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
296             0                               1                         0
74              1                               1                         1
164             1                               1                         1
292             0                               0                         0
89              1                               1                         1
147             1                               1                         1
7               1                               1                         1
297             0                               0                         0
112             1                               1                         1
126             1                               1                         1

In [37]:
from sklearn.metrics import recall_score, precision_score, f1_score

print("For Logistic Regression Model")

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred1))
print("\n")
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic Regression Model

Confusion Matrix:

[[26  6]
 [ 0 29]]


Precision -  0.8285714285714286
Recall -  1.0
F1 score -  0.90625


In [38]:
print("For Decision Tree Model")

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred2))
print("\n")
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For Decision Tree Model

Confusion Matrix:

[[26  6]
 [ 2 27]]


Precision -  0.8181818181818182
Recall -  0.9310344827586207
F1 score -  0.8709677419354839
